gochain/gochain

- p2p/server.go
Cherry-pick https://github.com/ethereum/go-ethereum/pull/17260
> p2p: fix rare deadlock in Stop

- p2p/discover/table.go
- p2p/discv5/net_test.go
- p2p/discv5/table.go
- swarm/api/manifest.go
- trie/node.go
- trie/trie.go
Cherry-pick https://github.com/ethereum/go-ethereum/pull/17265
> p2p, swarm, trie: avoid copying arrays in loops

- release.sh
> v before version tag to work with go mod

- Gopkg.lock
- Gopkg.toml
- crypto/bn256/cloudflare/gfp_amd64.s
- crypto/bn256/cloudflare/gfp_decl.go
- crypto/bn256/google/bn256.go
- crypto/bn256/google/curve.go
- crypto/bn256/google/twist.go
- crypto/secp256k1/libsecp256k1/src/null.go
From upstream https://github.com/ethereum/go-ethereum/pull/17368
> crypto/bn256: fix issues caused by Go 1.11

- eth/handler.go
This is a trace from the testnet. This block announcement operation was very slow and it also prevented further message processing from that peer.
This PR improves tracing and also moves the blocking work into a goroutine so that peer message handling can continue.
> eth: unblock msg handling by processing block announcements in a goroutine

- eth/peer.go
This PR increases the size of the buffered `queuedTxs` channel, lowers the log level for discarded txs, and batches up the txs before sending.
The batch logic is borrowed from the tx pool https://github.com/gochain-io/gochain/blob/master/core/tx_pool.go#L469-L477
> eth: batch queuedTxs broadcasts

- core/bloombits/generator.go
- ethdb/database_test.go
- ethdb/memory_database.go
* ethdb: fix memory database
* core: fix bloombits checking
* core: minor polish
> core, ethdb: two tiny fixes

- core/blockchain.go
- core/headerchain.go
In #266 the tie-break logic was updated, but that procedure was actually duplicated in another place - this PR adds a common function to share between both sites.
> core: share tie-break logic between headerchain and blockchain

- Gopkg.lock
- core/blockchain.go
- core/blockchain_test.go
- core/state/statedb.go
- core/state/sync.go
- eth/api_tracer.go
- eth/downloader/statesync.go
- les/odr_requests.go
- trie/database.go
- trie/encoding.go
- trie/hasher.go
- trie/iterator.go
- trie/node.go
- trie/proof.go
- trie/proof_test.go
- trie/secure_trie.go
- trie/sync.go
- trie/sync_test.go
- trie/trie.go
This PR updates `package trie` and related usages.
> trie: update trie package

- node/api.go
- node/config.go
- node/node.go
- rpc/client.go
- rpc/doc.go
- rpc/endpoints.go
- rpc/http.go
- rpc/http_test.go
- rpc/inproc.go
- rpc/ipc.go
- rpc/json.go
- rpc/server.go
- rpc/utils.go
- rpc/websocket.go
- rpc/websocket_test.go
This PR updates `package rpc` from upstream.
> rpc, node: update rpc package

- eth/downloader/downloader.go
This PR raises the log level of some synchronization messages.
> eth/downloader: improve sync logging

- core/blockchain.go
- core/headerchain.go
- core/tx_pool.go
This PR add some log messages for chain reorganizations and pool resets.
> core: log more about reorg and reset

- core/headerchain.go
This PR reduces log spam by only logging header chain reorganizations which are *significant* (not just a new single block). This was especially spammy during a sync:
```
INFO [10-29|18:39:06] Reorganizing header chain                oldnum=335274 newnum=335275 oldtd=1622690 newtd=1622695 oldhash=3d4e2e…6fc251 newhash=4022a0…fba318 newparent=3d4e2e…6fc251
INFO [10-29|18:39:06] Reorganized header chain                 dur=57.263µs
INFO [10-29|18:39:06] Reorganizing header chain                oldnum=335275 newnum=335276 oldtd=1622695 newtd=1622700 oldhash=4022a0…fba318 newhash=fff3f2…c93803 newparent=4022a0…fba318
INFO [10-29|18:39:06] Reorganized header chain                 dur=55.231µs
INFO [10-29|18:39:06] Reorganizing header chain                oldnum=335276 newnum=335277 …
```
> core: only log about significant header reorganizations

- core/tx_pool.go
This PR reduces log spam from tx pool resets which are just a single block (in the same vein as #306).
> core: only log about significant pool resets

- eth/handler.go
- eth/sync.go
This PR is an alternative deadlock prevention to #303.
> eth: sync peers with same total difficulty but different hashes

- core/blockchain.go
This PR fixes a shutdown panic from a misused `sync.WaitGroup`. When `Add()` is called after `Wait()`, a panic occurs: `panic: sync: WaitGroup is reused before previous Wait has returned`. This can happen on shutdown (did happen on testnet and caused head state to be lost) because there was nothing stopping a new operation from calling `WaitGroup.Add()` once shutdown has begun. In order to add to the wait group safely, we not only need to check if the `quit` channel has been closed, but we also need to do this atomically with the `Add()` call. This change adds a `sync.RWMutex` for this purpose. It is read locked while checking if `quit` is closed and  calling `Add()` (`BlockChain.wgAdd()`), and write locked while closing `quit` (`BlockChain.closeQuit()`) - this ensures that when `Wait()` …
> core: prevent BlockChain.Stop() panic

- accounts/abi/bind/backends/simulated.go
- accounts/usbwallet/ledger.go
- accounts/usbwallet/trezor.go
- core/blockchain.go
- core/tx_pool.go
- core/tx_pool_test.go
- core/types/transaction.go
- core/types/transaction_signing.go
- core/types/transaction_signing_test.go
- core/types/transaction_test.go
- eth/gasprice/gasprice.go
- eth/handler.go
- eth/helper_test.go
- eth/peer.go
- goclient/ethclient.go
- goclient/signer.go
- internal/ethapi/api.go
- les/handler.go
- light/odr_util.go
- light/txpool.go
- miner/worker.go
- mobile/types.go
- p2p/message.go
- p2p/rlpx.go
- rlp/decode.go
- rlp/encode.go
- tests/transaction_test_util.go
This PR removes insignificant trace spans and unused contexts.
> remove insignificant traces and ctx

- consensus/clique/clique.go
- miner/unconfirmed.go
- miner/worker.go
This PR changes some log messages which appeared more severe than they actually are.
> consensus/clique, miner: reduce log errs

- Gopkg.lock
- flock/flock.go
- flock/flock_plan9.go
- flock/flock_solaris.go
- flock/flock_unix.go
- flock/flock_windows.go
- node/node.go
> flock, node: embed missing flock dependency

- miner/worker.go
This PR enhances the worker commit deadline by cutting short in time for the end of the period.
> consensus/clique, miner: enhance worker commit deadline

- .circleci/config.yml
- Gopkg.lock
- internal/debug/flags.go
This PR should restore metrics which were inadvertently turned off.
> Metrics fix

- core/blockchain.go
- core/blockchain_insert.go
- core/blockchain_test.go
- core/tx_cacher.go
> core: polish side chain importer

- core/types/block.go
- core/types/gen_header_json.go
Reverting #335 and cf6ccaa81a37a6bd2610f2f1187868b32f8abc14
> core/types: revert nilable fields

- cmd/gochain/config.go
- eth/backend.go
- eth/config.go
- les/backend.go
This PR completes wiring of the `ConstantinopleOverride` flag.
> fix constantinople override support

- core/vm/evm.go
- core/vm/gas_table.go
- core/vm/interpreter.go
This PR updates `package vm` from upstream.
> core/vm: update package vm from upstream

- core/genesis-test.json
- params/config.go
- params/version.go
This PR hard codes the testnet constantinople fork for block #4081350.
Towards #332.
> core, params: set testnet constantinople fork for block #4081350

- core/types/block.go
- core/types/gen_header_json.go
> core/types: revert required signers/voters header fields

- eth/handler.go
This PR fixes a bug introduced in #376.
> eth: bug fix for ProtocolManger heighter

- core/rawdb/accessors_metadata.go
- eth/backend.go
This PR picks some database version fixes and improvements from upstream.
> core/rawdb, eth: fix database version

- accounts/accounts.go
- accounts/accounts_test.go
These were overlooked when merging from upstream. Aligning with other usages.
> fix data signing

- core/blockchain.go
- core/rawdb/accessors_chain.go
- core/rawdb/accessors_chain_test.go
- core/rawdb/accessors_indexes.go
- core/rawdb/accessors_indexes_test.go
- core/rawdb/schema.go
- core/state/statedb.go
- core/state_processor.go
- core/types/block.go
- core/types/gen_log_json.go
- core/types/gen_receipt_json.go
- core/types/gen_tx_json.go
- core/types/log.go
- core/types/receipt.go
- core/types/transaction.go
- core/types/transaction_signing.go
- core/types/transaction_test.go
- internal/ethapi/api.go
- les/handler.go
- les/handler_test.go
- les/protocol.go
- miner/worker.go
- params/version.go
This PR upgrades the database format to be more efficient by removing duplicate info and assembling it on read instead. From upstream.
> core: upgrade db

- p2p/rlpx.go
This PR removes some excess logging I added and that has only been noisy and not useful.
> p2p: reduce rlpx logging

- cmd/utils/flags.go
- crypto/account.go
- go.sum
Creates tests accounts outside the keystore (keystore is very slow).
> Faster local startup

- goclient/goclient.go
Fixing a bug discovered via chainload https://github.com/gochain/chainload/issues/26
> goclient: fix latest block num

- accounts/keystore/keystore_test.go
- miner/worker.go
- miner/worker_test.go
This PR fixes some races that were breaking tests.
> miner: fix test race

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- consensus/clique/gochain.go
- core/genesis-main.json
- core/genesis-test.json
- core/state_transition.go
- core/vm/evm.go
- params/config.go
https://github.com/gochain/gips/issues/35
> WIP: gip-35: add hafthor fork to split rewards; configure testnet
