gochain/gochain

- core/blockchain.go
- eth/downloader/downloader.go
- eth/downloader/downloader_test.go
- eth/downloader/fakepeer.go
- eth/downloader/queue.go
- eth/downloader/types.go
- eth/fetcher/fetcher.go
- eth/fetcher/fetcher_test.go
- eth/handler.go
- miner/worker.go
- remove some unnecessary uncles work and logging (log difficulty instead)
- defer high contention locking in `(*BlockChain) insertChain()` until necessary
> Remove Uncles and Reduce High Contention Mutex Work

- consensus/clique/clique.go
- core/block_validator.go
- core/block_validator_test.go
- core/blockchain.go
- core/blockchain_test.go
- core/types.go
- core/types/derive_sha.go
Traces show that `BlockChain.insertChain` is pretty heavily serialized:
This PR moves some block body validation into a separate goroutine, and spawns it before grabbing the lock.
> core: BlockChain.insertChain - validate body before locking

- consensus/clique/clique.go
- consensus/clique/fake.go
- consensus/clique/snapshot.go
- consensus/clique/snapshot_test.go
- consensus/consensus.go
- core/evm.go
- eth/fetcher/fetcher.go
- eth/handler.go
- eth/peer.go
- goclient/ethclient.go
- internal/ethapi/api.go
- les/handler.go
- light/odr_util.go
- light/txpool.go
- netstats/netstats.go
- p2p/message.go
- p2p/rlpx.go
- rlp/decode.go
- rlp/encode.go
This PR adds tracing to rlp encoding and decoding. Context isn't wired into the full stack everywhere, but every call at least gets a `context.Background()`.
> rlp: trace encoding and decoding

- .circleci/config.yml
This PR adds support for building and pushing docker images for branches, after manual approval. Images are pushed to docker hub and gcr.
> circleci: add manually triggered branch docker image build/push job

- core/blockchain.go
- core/state_processor.go
- miner/worker.go
This PR adds block parent hashes to some log lines, primarily to better understand what is happening in situations like this:
```
INFO [09-19|16:36:56] Commit new mining work                   number=1424647 diff=4 txs=551   elapsed=160.864ms
INFO [09-19|16:36:57] Commit new mining work                   number=1424647 diff=4 txs=572   elapsed=183.491ms
INFO [09-19|16:36:57] Commit new mining work                   number=1424647 diff=4 txs=582   elapsed=177.180ms
INFO [09-19|16:36:57] Commit new mining work                   number=1424647 diff=4 txs=588   elapsed=189.729ms
INFO [09-19|16:36:57] Commit new mining work                   number=1424647 diff=4 txs=617   elapsed=190.811ms
INFO [09-19|16:36:57] Commit new mining work                   number=1424647 diff=4 txs=628 …
```
> core, miner: log parent hash

- core/blockchain.go
- miner/worker.go
When encountering two chain heads with the same block number and total difficulty, a random one would be chosen as canonical with a 50/50 chance. This could happen if a single node sends out two different versions of a block (with different txs), or it could be two arbitrary length competing branches. In either case, it's not clear who should win (either choice is valid). This PR proposes choosing the block with the most gas used, before falling back to randomization. In the length-1 case, the 'bigger' block is the obvious choice. In the arbitrary length case, the history would have to be inspected to make a more informed choice, but this method is no worse than the old. In both cases, all nodes on the chain will now make the same deterministic choice (when the gas used is different), …
> core: use deterministic same-difficulty tie breaker

- event/feed.go
- event/feed_test.go
In #194 the feed send logic was adjusted to unsubscribe any blocking channels which time out. This is actually a pretty severe penalty for slow receivers, since they may only be blocked temporarily but would be unsubscribed permanently. Instead, we can just drop the value and continue on.
> event: don't unsubscribe on feed timeouts

- consensus/clique/clique.go
- consensus/clique/fake.go
- consensus/consensus.go
- core/chain_makers.go
- eth/handler.go
- miner/worker.go
This PR adds a deadline so that block assembly is short-circuited if the block timestamp passes. This will keep block times closer to the configured period, even if more txs could have been included for a more full block. The block broadcast was also adjusted from sqrt(peers) to all peers.
> consensus, core, miner: strict block finalization deadline

- trie/secure_trie.go
- trie/secure_trie_test.go
This commit adds a cache inside `trie.SecureTrie` to avoid duplicate calls to `hashKey()`. This saves a significant amount of time during `ApplyTransaction()` as most hashes are duplicates in large blocks.
> Add SecureTrie hash cache.

- accounts/abi/bind/backends/simulated.go
- core/blockchain.go
- core/tx_pool.go
- eth/api.go
- eth/api_backend.go
- eth/api_tracer.go
- eth/handler.go
- eth/sync.go
- miner/worker.go
- netstats/netstats.go
This PR modifies `core.Blockchain` by making two fields atomic values (no longer requiring the whole struct mutex to access), and adding a receipts cache.
> core: make some blockchain fields atomic instead of using whole struct lock

- rlp/decode.go
- rlp/encode.go
The RLP tracing takes up the overwhelming amount of tracing which makes it difficult to see any other type of tracing. Also, RLP is fast so it always reports span times of 0-1ms.
> rlp: Remove tracing

- ethdb/db.go
This commit sizes the header cache 100x larger than the body and
receipt cache. Header files are significantly smaller and accessed
more frequently.
> ethdb: Increase header LRU cache size.

- core/events.go
This PR makes non-blocking feed sends block, rather than drop work, when the channel is full. Txs still drop for now because they are a little different (sent while holding the tx pool lock; additional batching mechanism already exists; all pending txs get rebroadcast periodically anyways).
> core: make non-blocking feed sends (other than tx) block again rather than drop work

- accounts/abi/bind/backends/simulated.go
- core/blockchain.go
- core/blockchain_test.go
- core/chain_indexer.go
- core/events.go
- core/tx_pool.go
- core/tx_pool_test.go
- eth/api_backend.go
- eth/filters/filter.go
- eth/filters/filter_system.go
- eth/filters/filter_system_test.go
- eth/handler.go
- eth/helper_test.go
- eth/protocol.go
- internal/ethapi/backend.go
- les/api_backend.go
- les/handler.go
- les/server.go
- light/lightchain.go
- light/txpool.go
- miner/worker.go
- netstats/netstats.go
This PR is a follow up from #289. It allows feed subscribers to associate a `name` with the channel, and if the initial send is blocked then the delay is measured and logged along with the `name` of the channel that was full. The timeout was also restored to drop the send attempt (and log about it) if it takes longer than `500ms`. (`NewTxsEvent`/`NewTxsFeed` is still an exception.)
> core, eth, les, light: name feed subscribers; log feed delay times; add conservative feed timeout

- consensus/clique/clique.go
This PR adjusts block sealing. The old behavior (which I misunderstood) was to wait until a block's timestamp has passed (plus some delay for out-of-turn) to send it out - however this undermines the new deadline (#278 #288) feature and wastes time that peers could otherwise spend processing the block in order to be ready for assembling the next one on time. Instead, we now send out *in-turn* blocks immediately, and only wait for out-of-turn (which go out staggered in priority order, as before). The out-of-turn wiggle time was also reduced, as well as the block signing work moved up before the delay calculation.
> consensus/clique: finish sealing before delay; no delay for in-turn; reduce wiggle time

- consensus/clique/clique.go
- consensus/clique/clique_test.go
This PR is a follow up from #291, which moves the broadcast time for out-of-turn blocks from the *end of the period* to the *deadline*. The staggered delay is still used, but starts earlier (deadline is 1/3 of period right now) which will improve performance and produce a more gradual slowdown when signing out-of-turn - i.e. if one node is down, we just pay the `100ms` delay time, instead of waiting until the end of the period first (an extra ~`3.3s`).
> consensus/clique: delay out-of-turn broadcasts from deadline, rather than end of period

- core/events.go
- core/tx_pool.go
This PR improves the tx batching from the pool by delaying a bit to allow larger batches to accumulate, which allows the tx feed to operate more normally (like the others) and block instead of dropping immediately. The expected effect is to 1) build up larger batches and 2) have back pressure when blocked so that real queued work gets done instead of the batcher just spinning and dropping a bunch of tx batches of single txs. This should lead to 3) dropping less txs overall and logging more visibly when we do. When blocked, the tx pool itself will not be blocked since there is still a (huge) feed buffer channel in between that would also need to fill completely. In the worst case, log spam should be greatly reduced since drops are effectively rate limited by the timeout - so we'll see a …
> core: improve tx pool batching; align tx feed with others

- netstats/netstats.go
This PR adds a `transactionCount` field to the data sent to netstats, so that it may be used in place of checking the length of the `transactions` field. This was the only use of the `transactions` field (hashes only, but still a waste to send them all), so it can be removed in the future after netstats has been updated.
> netstats: add transactionCount field

- eth/filters/filter_system.go
- eth/handler.go
- miner/worker.go
This PR increases the size of the `NewTxsEvent` feed subscriber buffers (which were still sized based on the geth pool default config), and also changes the `worker` to process events in batch. The goal is to reduce the number of feed send delays/drops on the proxies:
> eth, miner: increase NewTxsEvent subscriber channel buffers; worker - process events in batch

- core/tx_pool.go
This PR restores old tx pool ChainHeadEvent handling, which is more precise and not as costly as previously thought.
> core: restore old tx pool ChainHeadEvent handling

- eth/downloader/api.go
- eth/downloader/downloader.go
- eth/downloader/downloader_test.go
- eth/downloader/fakepeer.go
- eth/downloader/queue.go
- eth/downloader/statesync.go
This PR updates `package downloader` from upstream, for the 'mini-reorg protection' in particular.
> eth/downloader: update

- common/db.go
- core/blockchain.go
- core/headerchain.go
- core/rawdb/accessors_chain.go
- core/rawdb/accessors_indexes.go
- core/rawdb/accessors_metadata.go
- core/rawdb/interfaces.go
- core/rawdb/retry.go
- eth/bloombits.go
- ethdb/file_segment.go
- ethdb/file_segment_test.go
- ethdb/ldb_segment.go
- ethdb/memory_database.go
- ethdb/table.go
- ethdb/table_test.go
- les/odr_test.go
- light/nodeset.go
- light/txpool.go
This PR adds a `rawdb.Must` function for retrying various db operations when appropriate (e.g. s3 timeouts), rather than shutting down suddenly with a `log.Crit` call.
> core, core/rawdb, eth, light: retry rawdb failures with backoff instead of shutting down

- cmd/gochain-ethdb/keys.go
- cmd/gochain-ethdb/main.go
- ethdb/db.go
Prints all keys (hex-encoded) and their value sizes in a tab-delimited format.
```sh
$ gochain-ethdb keys -table global /path/to/chaindata
```
> Add 'gochain-ethdb keys' command.

- accounts/abi/bind/backends/simulated.go
- eth/api_backend.go
- eth/filters/api.go
- eth/filters/bench_test.go
- eth/filters/filter.go
- eth/filters/filter_system.go
- eth/filters/filter_system_test.go
- eth/filters/filter_test.go
- interfaces.go
- mobile/ethereum.go
This PR updates `package filters` from upstream. It was initially pulled in hopes of fixing the `not found` filter error (didn't help), but is good to have anyways.
> eth/filters: update package filters

- core/rawdb/accessors_indexes.go
- eth/bloombits.go
- eth/filters/filter_system_test.go
- light/odr_util.go
- light/postprocess.go
This PR aligns `rawdb.ReadBloomBits` with the other read methods by using the retry logic and returning empty data instead of an error when a value is 'not found'.
> core/rawdb: retry ReadBloomBits and ignore ErrNotFound

- miner/worker.go
This PR adjusts the worker commit start delay to make it more stable.
Previously, if `timestamp` was earlier than the `parent`'s, then it was set to `parent + 1`, but if it was in first second after the `parent`, then it went through undelayed. This means that a later arrival could actually go through sooner. Instead, anything earlier than `parent + 1` should be delayed until `parent + 1`, so no ordering is reversed - and the whole first second is open to receive the next canonical block before mining again. (Also, we don't waste any mining time since we are recommitting up to every second anyways)
This might help with the patterned propagation delays we've been seeing on the testnet:
> miner: stabilize worker commit start delay

- core/blockchain.go
- miner/worker.go
This PR enhances tracing with more named spans and by 'always sampling' some per-block spans.
> WIP - miner: more tracing of miner commit methods

- common/compiler/solidity.go
This PR updates `common/compiler` from upstream.
Fixes #321
> common/compiler: capture runtime code and source maps

- miner/worker.go
This PR reverts #320.
This was actually working against us, because if the period deadline is hit, then less time than the limit was used and the work was not finished. Meanwhile, the previous candidates for this block had the whole time limit available and likely the same amount of work (unless the work *just arrived*), so the final deadline block usually ends up being smaller (sometimes even 0 txs) than the previous candidate from having less time, but wins by default. Instead we want to prefer blocks which had the full time limit.
> miner: revert worker commit deadline

- internal/ethapi/api.go
From upstream. This should smooth out some occasional nonce issues under high volume.
> internal/ethapi: get pending tx count from pool

- cmd/gochain/config.go
- cmd/gochain/main.go
- cmd/gochain/usage.go
- cmd/utils/flags.go
- core/genesis.go
This PR adds a `--local` flag to run a local chain for development. This is similar to `--dev`, but the data persists (defaults to `.local`). By default, 10 accounts are created and their address/key pairs are logged during configuration. An optional `--local.fund` flag can be used to pass a comma separated list of addresses to fund instead.
Example usage via docker:
```sh
> docker run --name local_node -p 8545:8545 gochain/gochain:local gochain --local
INFO [02-04|20:51:46] Maximum peer count                       ETH=25 LES=0 total=25
INFO [02-04|20:51:47] Signing with account                     address=0xAB6667F7C4F1d5C82cA20170DbD9FB603441471e
INFO [02-04|20:52:13] Pre-funded accounts:
Address						Key
0x5725A325836eb783f993a1007141599109125412 …
```
> cmd, core: add --local flag for persistent dev chains

- cmd/evm/runner.go
- cmd/evm/staterunner.go
- cmd/puppeth/wizard_genesis.go
- cmd/utils/flags.go
- core/genesis.go
- core/vm/gas_table.go
- core/vm/json_logger.go
- params/config.go
- tests/block_test.go
- tests/init.go
- tests/init_test.go
- tests/rlp_test_util.go
- tests/state_test.go
- tests/transaction_test_util.go
- tests/vm_test.go
This PR pulls the ConstantinopleFix changes from upstream, along with other supporting changes.
> This PR adds a new fork which disables EIP-1283. Internally it's called Petersburg,
but the genesis/config field is ConstantinopleFix.
> This PR also defaults to using the same ConstantinopleFix number as whatever
Constantinople is set to. That is, it will default to mainnet behaviour if ConstantinopleFix
is not set.This means that for private networks which have already transitioned
to Constantinople, this PR will break the network unless ConstantinopleFix is
explicitly set!
Towards #332
> core, cmd/puppeth: implement constantinople fix, disable EIP-1283

- cmd/utils/flags.go
This PR sets the network ID to the chain ID for local and dev, and rejects the network id flag.
> cmd/utils: set netId to chainId for local and dev

- core/genesis.go
This PR changes the random net/chain ID generation from a 64 bit integer to a 32 bit integer plus 1000 (to push it above 'regular' looking IDs). This will keep the IDs well under 53 bits, which is the max web3js can handle.
> core: limit random chain ID range so as not to overflow web3js

- cmd/utils/flags.go
- core/genesis.go
`--local.fund` now accepts an optional balance value paired with each address. For example: 
```sh
--local.fund 0xa:1,0xb,0xc:1000
```
Fixes #360
> cmd/utils, core: support custom genesis alloc balances for local nodes

- core/genesis-main.json
- params/config.go
This PR sets the mainnet Constantinople fork for block number 5,100,000 - around 5:12AM, Thursday March 7th UTC.
Closes #332
> core, params: set mainnet constantinople fork for block #5100000

- .circleci/config.yml
- Dockerfile
Go 1.12 was released. This PR upgrades Docker and CI from go1.12beta2 to go1.12.
> upgrade Dockerfile and CI to go1.12

- Makefile
Hi, this PR updates the makefile to compare the current go version to minimum required version. The makefile exits with an error message if the current version is older than the required version. Please let me know how it looks and any improvements you can suggest.
> Add Go version check to Makefile #369

- internal/debug/flags.go
- log/format.go
This PR adds a `--logging.stackdriver` flag to enable JSON logging with stackdriver compatible keys.
~Draft for now until I can determine if the existing severity/levels are good enough, or need to be modified.~ They seems to work.
> add --logging.stackdriver flag

- core/blockchain.go
- core/rawdb/accessors_chain.go
- ethdb/file_segment.go
- go.mod
- go.sum
- params/version.go
This PR moves the canonical hash mappings (# -> hash) from the header table to the global table, so that they stay local instead of ending up in archived header table files. This should reduce memory usage from mmap-ed files, and was likely a mistake/oversight in the first place.
> core/rawdb: move canonical hash mapping from header table to global; fix mmap leak

- .circleci/config.yml
This is a no-op change cleaning up the CI config in order to trigger a build with a newer go release (1.13.7).
> circleci: remove noise from config; trigger 1.13.x build

- cmd/utils/flags.go
- eth/config.go
- eth/gasprice/gasprice.go
- eth/gasprice/gasprice_test.go
This PR prepares for https://github.com/gochain/gips/issues/29 by increasing the oracle max gas value and making it flag configurable.
> increase oracle max and make flag configurable

- core/genesis-test.json
- core/state_transition.go
- core/tx_pool.go
- eth/backend.go
- eth/config.go
- eth/gasprice/gasprice.go
- eth/gasprice/gasprice_test.go
- internal/ethapi/api.go
- params/config.go
- params/version.go
This PR prepares for gochain/gips/issues/30 by adding a fork block switch to burn all gas fees instead of sending them to the signer of the block, and to reconfigure the gas price for gochain/gips/issues/29 at the same time.
Automatically reconfigure gas price parameters for GIP-29, at or around the Darvaza block.
> GIP 29&30: add Darvaza fork to burn gas fees and reconfigure gas price
